language: node_js
node_js:
  - 7
  - 6
  - 5
  - 4
cache: node_modules
after_success:
  - nyc report --reporter text-lcov | codeclimate-test-reporter
  - nyc report --reporter lcov && codecov
  - nyc report --reporter text-lcov | coveralls
